"""
research_agent/literature_generator.py
----------------------------------------
Literature synthesis and output formatting.
"""
from typing import List, Dict
from langchain_openai import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from research_agent.config import Config

SYNTHESIS_PROMPT = PromptTemplate(
    input_variables=["topic", "num_papers", "summaries"],
    template="""You are a senior AI researcher writing the literature review section of a research paper.

Research Topic: {topic}
Number of papers analyzed: {num_papers}

Below are structured summaries of each paper:

{summaries}

Write a literature review of exactly 3 paragraphs following this structure:

PARAGRAPH 1 — Research Trends & Context
Describe the overall research trajectory in this area. What paradigms or approaches have been dominant? How has the field evolved?

PARAGRAPH 2 — Methods & Key Contributions
Synthesize the major methodological approaches, architectures, and frameworks. Highlight landmark results. Reference papers by title or lead author where appropriate.

PARAGRAPH 3 — Research Gaps & Future Directions
Identify what is missing, under-explored, or explicitly stated as a limitation. Frame these gaps to motivate future work.

Formatting rules:
- Write in formal, academic English
- Use flowing paragraphs — no bullet points, no headings
- Be specific: name models, datasets, metrics where present
- Do not include anything outside the three paragraphs

LITERATURE REVIEW:""",
)


class LiteratureGenerator:
    """Synthesizes per-paper summaries into a cohesive literature review."""

    def __init__(self, config: Config) -> None:
        self.config = config
        llm = ChatOpenAI(
            model=config.synthesis_model,
            temperature=config.synthesis_temperature,
            openai_api_key=config.openai_api_key,
        )
        self._chain = SYNTHESIS_PROMPT | llm | StrOutputParser()

    def generate(self, topic: str, papers: List[Dict]) -> str:
        print("[LiteratureGenerator] Synthesizing review...\n")
        summaries_block = ""
        for i, p in enumerate(papers, 1):
            summaries_block += f"[{i}] {p['title']}\n{p['summary']}\n\n"
        result = self._chain.invoke({
            "topic":      topic,
            "num_papers": str(len(papers)),
            "summaries":  summaries_block,
        })
        print("[LiteratureGenerator] Done.\n")
        return result.strip()

    @staticmethod
    def format_output(topic: str, papers: List[Dict], review: str) -> str:
        sep = "=" * 72
        refs = ""
        for i, p in enumerate(papers, 1):
            authors = p["authors"][:3]
            if len(p["authors"]) > 3:
                authors = authors + ["et al."]
            year = p["date"][:4]
            refs += f"  [{i}] {', '.join(authors)} ({year}). {p['title']}.\n       {p['url']}\n"
        return (
            f"\n{sep}\n"
            f"  AUTOMATED LITERATURE REVIEW\n"
            f"  Topic    : {topic}\n"
            f"  Papers   : {len(papers)}\n"
            f"{sep}\n\n"
            f"{review}\n\n"
            f"{sep}\n  REFERENCES\n{sep}\n"
            f"{refs}{sep}\n"
        )

    @staticmethod
    def to_latex(topic: str, papers: List[Dict], review: str) -> str:
        escape = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
                  "_": r"\_", "{": r"\{", "}": r"\}"}
        safe = review
        for c, r in escape.items():
            safe = safe.replace(c, r)
        bibitems = ""
        for i, p in enumerate(papers, 1):
            bibitems += (
                f"\\bibitem{{ref{i}}}\n"
                f"  {', '.join(p['authors'][:3])} ({p['date'][:4]}).\n"
                f"  \\textit{{{p['title']}}}.\n"
                f"  \\url{{{p['url']}}}\n\n"
            )
        return (
            f"% Generated by Research Literature Review Agent\n"
            f"\\section{{Related Work}}\n\n{safe}\n\n"
            f"\\begin{{thebibliography}}{{99}}\n{bibitems}\\end{{thebibliography}}\n"
        )
